---
language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11
    - os: osx
      osx_image: xcode12
    - os: windows
      before_install:
        - choco install make
        - choco install zip
        - choco install python
        - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        - C:\Python38\python3 get-pip.py
        - C:\Python38\python3 -m pip install wheel scons
addons:
  apt:
    packages:
      - git
      - gdb
      - curl
      - cmake
      - libx11-dev
      - libglu1-mesa-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - zlib1g-dev
      - libasound2-dev
      - libgtk2.0-dev
      - libjack-jackd2-dev
      - jq
      - scons
  homebrew:
    packages:
      - git
      - wget
      - cmake
      - autoconf
      - automake
      - libtool
      - jq
      - python
      - scons
git:
  submodules: true
env:
  global:
    - MAKEFLAGS="-j 2"
install:
  - mkdir -p "${HOME}"/Rack
  - pushd "${HOME}"/Rack
  - curl -o Rack-SDK.zip https://vcvrack.com/downloads/Rack-SDK-1.1.6.zip
  - unzip Rack-SDK.zip
  - popd
script:
  - scons -j2 test
  - export RACK_DIR="${HOME}"/Rack/Rack-SDK
  - make -j2 dep
  - make -j2 dist
notifications:
  email: false
