---
slug: KautenjaDSP-PotatoChips
version: '1.6.1'
license: GPL-3.0-or-later
name: KautenjaDSP Potato Chips
brand: KautenjaDSP
author: Christian Kauten
authorEmail: KautenjaDSP@gmail.com
authorUrl: https://kautenja.github.io/
sourceUrl: https://github.com/Kautenja/PotatoChips
changelogUrl: https://github.com/Kautenja/PotatoChips/blob/master/CHANGELOG.md
modules:
  - slug: AY_3_8910
    name: AY-3-8910
    description: An emulation of the General Instrument AY-3-8910 chip.
    manualUrl: https://github.com/Kautenja/PotatoChips/releases/latest/download/AY_3_8910.pdf
    tags:
      - Oscillator
      - Polyphonic
  - slug: POKEY
    name: POKEY
    description: An emulation of the Atari POKEY chip.
    manualUrl: https://github.com/Kautenja/PotatoChips/releases/latest/download/POKEY.pdf
    tags:
      - Oscillator
      - Polyphonic
  # - slug: SCC
  #   name: SCC
  #   description: An emulation of the Konami SCC wavetable chip.
  #   manualUrl: https://github.com/Kautenja/PotatoChips/releases/latest/download/SCC.pdf
  #   tags:
  #     - Oscillator
  - slug: VRC6
    name: VRC6
    description: An emulation of the Konami VRC6 chip from certain Nintendo Entertainment System (NES) cartridges.
    manualUrl: https://github.com/Kautenja/PotatoChips/releases/latest/download/VRC6.pdf
    tags:
      - Oscillator
      - Polyphonic
  - slug: '106'
    name: '106'
    description: An emulation of the Namco 106 wavetable chip from certain Nintendo Entertainment System (NES) cartridges.
    manualUrl: https://github.com/Kautenja/PotatoChips/releases/latest/download/106.pdf
    tags:
      - Oscillator
      - Polyphonic
  # - slug: TURBO_GRAFX_16
  #   name: Turbo Grafx 16
  #   description: An emulation of the NEC Turbo Grafx 16 wavetable chip.
  #   manualUrl: https://github.com/Kautenja/PotatoChips/releases/latest/download/TURBO_GRAFX_16.pdf
  #   tags:
  #     - Oscillator
  - slug: GBS
    name: GBS
    description: An emulation of the Nintendo Gameboy Sound System chip.
    manualUrl: https://github.com/Kautenja/PotatoChips/releases/latest/download/GBS.pdf
    tags:
      - Oscillator
      - Noise
      - Polyphonic
  # - slug: S_SMP
  #   name: S-SMP
  #   description: An emulation of the Sony S-SMP chip from the Super Nintendo Entertainment System (SNES).
  #   manualUrl: https://github.com/Kautenja/PotatoChips/releases/latest/download/S_SMP.pdf
  #   tags:
  #     - Oscillator
  #     - Echo
  - slug: 2A03
    name: 2A03
    description: An emulation of the Ricoh 2A03 chip from the Nintendo Entertainment System (NES).
    manualUrl: https://github.com/Kautenja/PotatoChips/releases/latest/download/2A03.pdf
    tags:
      - Oscillator
      - Noise
      - Polyphonic
  - slug: FME7
    name: FME7
    description: An emulation of the Sunsoft FME-7 chip from certain Nintendo Entertainment System (NES) cartridges.
    manualUrl: https://github.com/Kautenja/PotatoChips/releases/latest/download/FME7.pdf
    tags:
      - Oscillator
      - Polyphonic
  - slug: SN76489
    name: SN76489
    description: An emulation of the Texas Instruments SN76489 chip from the Sega Master System.
    manualUrl: https://github.com/Kautenja/PotatoChips/releases/latest/download/sn76489.pdf
    tags:
      - Oscillator
      - Noise
      - Polyphonic
  # - slug: '2413'
  #   name: '2413'
  #   description: An emulation of the Yamaha YM2413 FM synthesis chip from the Sega Mark III.
  #   manualUrl: https://github.com/Kautenja/PotatoChips/releases/latest/download/2413.pdf
  #   tags:
  #     - Oscillator
  #     - Noise
  # - slug: '2612'
  #   name: '2612'
  #   description: An emulation of the Yamaha YM2612 FM synthesis chip from the Sega Mega Drive.
  #   manualUrl: https://github.com/Kautenja/PotatoChips/releases/latest/download/2612.pdf
  #   tags:
  #     - Oscillator
  #     - Noise
